run:
  skip-dirs-use-default: false

linters:
  enable-all: true
  disable:
    - gochecknoinits
    - paralleltest
    - wrapcheck
    - gosec
    - gochecknoglobals
    - musttag
    - revive # consider enabling (e.g., require doc for all package externals)
    - depguard # irrelevant now
    - nonamedreturns # I like to (be able to judiciously) use named returns
    - exhaustruct # seems excessive & I often use this

    # Deprecated ones:
    - structcheck
    - interfacer
    - deadcode
    - varcheck
    - ifshort
    - exhaustivestruct
    - golint
    - maligned
    - nosnakecase
    - scopelint

gocyclo:
  min-complexity: 15

issues:
  exclude-use-default: false
