# Gochat Configuration

Chatter:
  # Select which chatter adapter to use; i.e. either "OpenAI" or "Gemini"
  Adapter: OpenAI

  # Select your default prompt here, if needed (e.g., "terse")
  DefaultPrompt:
  Prompts:
    terse: |
      Please give answers to all future prompts in as succinct a way as possible;
      preferably in a single sentence.

  Adapters:
    OpenAI:
      APIKey: YOUR_OPENAI_API_KEY
      Model: gpt-4-1106-preview # https://platform.openai.com/docs/models/gpt-4-and-gpt-4-turbo

    Gemini:
      APIKey: YOUR_GEMINI_API_KEY
      Model: gemini-pro # see https://ai.google.dev/models

Scriber:
  # Select which scriber adapter (if any) to use; i.e., either "Template" or "None"
  Adapter: None

  Adapters:
    # Templates used to format output when "Scriber = Template"
    TemplateScribe:
      SaveDir: transcripts
      SaveFile: chat.md
      Templates:
        Header: |
          # `gochat` - Transcript
          ## Started at {{ (.Time).Format "Mon Jan _2 15:04:05 MST 2006" }}
          ### _(Between `{{ .User }}` and `{{ .Chatter }}`)_

          ---
        Entry: |
          #### `{{ .Who }}`: _@{{ (.Time).Format "15:04:05" }}_
          {{ range $line := split .What "\n" }} > {{ $line }}{{ println }}{{ end }}
        Footer: |
          ---
          _(chat concluded at {{ (.Time).Format "Mon Jan _2 15:04:05 MST 2006" }})_
